### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hoijui** [simonchih/Random-Big-Rich-Man#1]
hey simon! :-)
i came across your game here, and quite like it. i would like to make some fixes on it, but would first like to ask whether you would be willing to release it under an open source or free software license.
in case you don't know how licensing/copyright of source-code works:
as long as you did not state any license, the default is applied, which is "All rights reserved". this means, i can not use, modify, or incorporate into my project, your work, without asking you specifically for everything, even though you put the code into the public, practically speaking, by putting it on github.
so if you would be ok with an open license, i would do that for this project, if it is ok for you. in that case, just tell me which license you prefer, and if you don't know about them, i can give you a short info there too, or you can simply read online about some of the most common open licenses for source code:
* GPL (my favourite)
* BSD
* MIT
* APL

PS: Legally speaking, you would also have to respect the licenses for the resources (images and audio) that you are using. so for example, if they are GPL, then you would have to make your project GPL too, or remove them. Of course, that is only a problem in practise if someone thinks it is a problem, which of course will never happen with your game. ;-)

anyway.. cool thing, and ride on! :-)

hoijui

**Comment by simonchih** [comment]
Hello, hoijui:
    Random Big Rich Man is open source and free to NO commerce usage. Thus
you can't make any money by selling this game or advertisement income or
any commerce usage.
I specified license on https://sourceforge.net/projects/randombigrich/:
GNU General Public License version 3.0 (GPLv3)
<https://sourceforge.net/directory/license:gplv3/>,
Creative Commons Attribution Non-Commercial License V2.0
<https://sourceforge.net/directory/license:ccanclv2/>

It's free to join my repository or create new project.
All images and audio file in this game are in other open source project or
free to NO commerce usage.
You would better to replace all images or audio if needed.

By the way, I think you can read or type Chinese, do you?

2017-12-07 0:40 GMT+08:00 hoijui <notifications@github.com>:

**Comment by hoijui** [comment]
...ouhh indeed, there it is, thank you! :-)
and .. no, sadly no chinese here.. my nickname only sounds somehow chinese, but it is a pure fantasy name.

i like the name you chose.. random big rich man! :D
it fits really well!
i remembered the game from my childhood, and in my memories it was so exciting and interesting, big and complex. when i look at it now, it is super boring. :D
ok... we played with much more relaxed rules back then: trading lands with each other, buying and selling them amongst each other, quasi alliances, ... maybe that was the difference.. the human element!
that would be much tougher for the AI i guess, and it would never be as much fun probably...
a good experience, for sure! :-)

i'll send you a pull request or something, one of these days. :-)

**Comment by hoijui** [comment]
License file and headers now present.
thanks for access! :-)
